# -*- coding: utf-8 -*-
"""TutorialNLtoCAD.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iwhA0lHWLRyXwgkcUL2jgXcEo9HaH369
"""

print("STEP 1: Installing the package from GitHub...")
!pip install -q git+https://github.com/mschongchulshin/NaturalLanguage-to-CAD.git
print("Installation complete.")


import json
from cad_generator import CADGenerator

print("\nSTEP 2: Initializing the generator...")
print("This may take a moment as the model is downloaded from Hugging Face Hub.")

generator = CADGenerator()
print("Generator is ready.")


print("\nSTEP 3: Generating JSON from your prompt...")

user_prompt = """
Draw a workspace layout. The grid unit is 10x10, and the origin is at robot R1's position (0,0).
There are two robots: R1 at (0,0) and R2 at (48,-8).
There are three conveyors: C1 at (-10,-20), C2 at (23,-7), and C3 at (50,-28).
There are four tables: T1 at (-6,-10), T2 at (10,-6), T3 at (36,-8), and T4 at (52,-20).
Finally, add two rectangular safety fences, F1 and F2.
"""

generated_json_str = generator.generate(user_prompt)


print("\n--- Generated JSON Result ---")
try:
    parsed_json = json.loads(generated_json_str)
    print(json.dumps(parsed_json, indent=2, ensure_ascii=False))
except json.JSONDecodeError:
    print("Warning: The model output was not valid JSON. Displaying raw text:")
    print(generated_json_str)

print("\nProcess finished.")

